### ISSUE TITLE
Shop not loading properly 

### ISSUE THREAD

**Issue by UgaBugaBoo** [OwOHamper/Valorant-item-shop-discord-bot#6]
When shop command is called, it just loads the first bundle and does not load anything else. 

![image](https://user-images.githubusercontent.com/7885525/128309395-c8ecd479-9b68-4e2d-b6cc-6c9fb4d49dd4.png)

Error in python :
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\LEGION-VEE\Desktop\item_shop_viewer.py", line 349, in on_message
    await message.channel.send(embed=embed)
  File "C:\Python39\lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Python39\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.image.url: Scheme "none" is not supported. Scheme must be one of ('http', 'https').

```

**Comment by teoobarca** [comment]
Prob because the image has no url in valorant-api.com You can try adding exception when the embeded image is assigned
