### ISSUE TITLE
Shop Doesn't Display

### ISSUE THREAD

**Issue by aierwin** [OwOHamper/Valorant-item-shop-discord-bot#9]
The Bot Is turned on and everything but when i run "!shop" it crashes after saying loading shop and displays this error

XGVALSTORE#0472 is connected
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "item_shop_viewer.py", line 345, in on_message
    skin_data = skins(entitlements_token, access_token, user_id)
  File "item_shop_viewer.py", line 219, in skins
    for row_small in content_data[row]:
TypeError: 'int' object is not iterable

**Comment by ghost** [comment]
same
